### ISSUE TITLE
Oh God… separate repo and separate pod for new version? 😟

### ISSUE THREAD

**Issue by ianbytchek** [PaddleHQ/Mac-Framework-V4#54]
But WHY?

**Comment by GregularExpressions** [comment]
Hey @ianbytchek are you referring to v3 and v4? This was for a couple of reasons:

1. We're continuing to support fixes for the deprecated v3 branch and wanted to keep the separate distribution channel for that.
2. v4 isn't a drop in replacement for v3, it has multiple improvements in models and paradigms that require some development time to adopt. We felt it was better that Sellers opt to move to it rather than we push it as an update.

Does it present an issue for you?

**Comment by ianbytchek** [comment]
No, but it's hurting my feelings and makes my eyes bleed.

Not that this can be undone or anything you wouldn't know already, but just to make a point:
1. SemVer implies that v3 → v4 is a breaking change. Only people who use `master` in their dependencies would get burned by this and frankly they 💯 deserve it. Maybe it would finally teach them a lesson.
2. One project. Multiple branches. That's what they are for amongst other great things. Apple [is doing it](https://github.com/apple) and [supports older versions](https://github.com/apple/swift/releases), [NodeJS](https://github.com/nodejs/node/branches) is doing it and [supports older versions](https://github.com/nodejs/node/tags), [FFmpeg](https://github.com/FFmpeg/FFmpeg/branches) is doing it and [supports older versions](https://github.com/FFmpeg/FFmpeg/releases), [so](https://github.com/python/cpython/branches), [are](https://github.com/ruby/ruby/branches), [all](https://github.com/golang/go/branches), [large](https://github.com/symfony/symfony/branches), [enough](https://github.com/zendframework/zendframework/branches), [projects](https://github.com/mysql/mysql-server/branches).

**Comment by GregularExpressions** [comment]
@ianbytchek thanks for the feedback, we'll bear it in mind next time.
